// Code generated by MockGen. DO NOT EDIT.
// Source: chat.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	chat "vine-agent/domain/chat"
	message "vine-agent/domain/message"

	gomock "github.com/golang/mock/gomock"
)

// MockChatModel is a mock of ChatModel interface.
type MockChatModel struct {
	ctrl     *gomock.Controller
	recorder *MockChatModelMockRecorder
}

// MockChatModelMockRecorder is the mock recorder for MockChatModel.
type MockChatModelMockRecorder struct {
	mock *MockChatModel
}

// NewMockChatModel creates a new mock instance.
func NewMockChatModel(ctrl *gomock.Controller) *MockChatModel {
	mock := &MockChatModel{ctrl: ctrl}
	mock.recorder = &MockChatModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatModel) EXPECT() *MockChatModelMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockChatModel) Generate(ctx context.Context, messages []message.Message, opts ...chat.OptionFunc) (*message.Message, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, messages}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Generate", varargs...)
	ret0, _ := ret[0].(*message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockChatModelMockRecorder) Generate(ctx, messages interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, messages}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockChatModel)(nil).Generate), varargs...)
}

// Stream mocks base method.
func (m *MockChatModel) Stream(ctx context.Context, messages []message.Message, opts ...chat.OptionFunc) (message.StreamMessageReader, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, messages}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Stream", varargs...)
	ret0, _ := ret[0].(message.StreamMessageReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stream indicates an expected call of Stream.
func (mr *MockChatModelMockRecorder) Stream(ctx, messages interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, messages}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockChatModel)(nil).Stream), varargs...)
}
