// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	profile "vine-agent/domain/memory/profile"
	message "vine-agent/domain/message"

	gomock "github.com/golang/mock/gomock"
)

// MockProfileRepository is a mock of ProfileRepository interface.
type MockProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProfileRepositoryMockRecorder
}

// MockProfileRepositoryMockRecorder is the mock recorder for MockProfileRepository.
type MockProfileRepositoryMockRecorder struct {
	mock *MockProfileRepository
}

// NewMockProfileRepository creates a new mock instance.
func NewMockProfileRepository(ctrl *gomock.Controller) *MockProfileRepository {
	mock := &MockProfileRepository{ctrl: ctrl}
	mock.recorder = &MockProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileRepository) EXPECT() *MockProfileRepositoryMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockProfileRepository) GetByUserID(ctx context.Context, userID string) (*profile.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*profile.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockProfileRepositoryMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockProfileRepository)(nil).GetByUserID), ctx, userID)
}

// Save mocks base method.
func (m *MockProfileRepository) Save(ctx context.Context, prof *profile.Profile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, prof)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockProfileRepositoryMockRecorder) Save(ctx, prof interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockProfileRepository)(nil).Save), ctx, prof)
}

// MockExtractor is a mock of Extractor interface.
type MockExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockExtractorMockRecorder
}

// MockExtractorMockRecorder is the mock recorder for MockExtractor.
type MockExtractorMockRecorder struct {
	mock *MockExtractor
}

// NewMockExtractor creates a new mock instance.
func NewMockExtractor(ctrl *gomock.Controller) *MockExtractor {
	mock := &MockExtractor{ctrl: ctrl}
	mock.recorder = &MockExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtractor) EXPECT() *MockExtractorMockRecorder {
	return m.recorder
}

// Extract mocks base method.
func (m *MockExtractor) Extract(ctx context.Context, messages []message.Message, existingPrefs, existingFacts []string) ([]string, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", ctx, messages, existingPrefs, existingFacts)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Extract indicates an expected call of Extract.
func (mr *MockExtractorMockRecorder) Extract(ctx, messages, existingPrefs, existingFacts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockExtractor)(nil).Extract), ctx, messages, existingPrefs, existingFacts)
}

// MockEvolutionService is a mock of EvolutionService interface.
type MockEvolutionService struct {
	ctrl     *gomock.Controller
	recorder *MockEvolutionServiceMockRecorder
}

// MockEvolutionServiceMockRecorder is the mock recorder for MockEvolutionService.
type MockEvolutionServiceMockRecorder struct {
	mock *MockEvolutionService
}

// NewMockEvolutionService creates a new mock instance.
func NewMockEvolutionService(ctrl *gomock.Controller) *MockEvolutionService {
	mock := &MockEvolutionService{ctrl: ctrl}
	mock.recorder = &MockEvolutionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvolutionService) EXPECT() *MockEvolutionServiceMockRecorder {
	return m.recorder
}

// Evolve mocks base method.
func (m *MockEvolutionService) Evolve(ctx context.Context, prof *profile.Profile, messages []message.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evolve", ctx, prof, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Evolve indicates an expected call of Evolve.
func (mr *MockEvolutionServiceMockRecorder) Evolve(ctx, prof, messages interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evolve", reflect.TypeOf((*MockEvolutionService)(nil).Evolve), ctx, prof, messages)
}
