// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	retrieval "vine-agent/domain/memory/retrieval"
	message "vine-agent/domain/message"

	gomock "github.com/golang/mock/gomock"
)

// MockRetrievalRepository is a mock of RetrievalRepository interface.
type MockRetrievalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRetrievalRepositoryMockRecorder
}

// MockRetrievalRepositoryMockRecorder is the mock recorder for MockRetrievalRepository.
type MockRetrievalRepositoryMockRecorder struct {
	mock *MockRetrievalRepository
}

// NewMockRetrievalRepository creates a new mock instance.
func NewMockRetrievalRepository(ctrl *gomock.Controller) *MockRetrievalRepository {
	mock := &MockRetrievalRepository{ctrl: ctrl}
	mock.recorder = &MockRetrievalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRetrievalRepository) EXPECT() *MockRetrievalRepositoryMockRecorder {
	return m.recorder
}

// DeleteBySession mocks base method.
func (m *MockRetrievalRepository) DeleteBySession(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBySession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBySession indicates an expected call of DeleteBySession.
func (mr *MockRetrievalRepositoryMockRecorder) DeleteBySession(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBySession", reflect.TypeOf((*MockRetrievalRepository)(nil).DeleteBySession), ctx, sessionID)
}

// Save mocks base method.
func (m *MockRetrievalRepository) Save(ctx context.Context, sessionID, userID string, msg message.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, sessionID, userID, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRetrievalRepositoryMockRecorder) Save(ctx, sessionID, userID, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRetrievalRepository)(nil).Save), ctx, sessionID, userID, msg)
}

// SearchSession mocks base method.
func (m *MockRetrievalRepository) SearchSession(ctx context.Context, sessionID, query string, limit int) ([]message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSession", ctx, sessionID, query, limit)
	ret0, _ := ret[0].([]message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSession indicates an expected call of SearchSession.
func (mr *MockRetrievalRepositoryMockRecorder) SearchSession(ctx, sessionID, query, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSession", reflect.TypeOf((*MockRetrievalRepository)(nil).SearchSession), ctx, sessionID, query, limit)
}

// SearchUser mocks base method.
func (m *MockRetrievalRepository) SearchUser(ctx context.Context, userID, query string, limit int) ([]retrieval.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUser", ctx, userID, query, limit)
	ret0, _ := ret[0].([]retrieval.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUser indicates an expected call of SearchUser.
func (mr *MockRetrievalRepositoryMockRecorder) SearchUser(ctx, userID, query, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUser", reflect.TypeOf((*MockRetrievalRepository)(nil).SearchUser), ctx, userID, query, limit)
}

// MockRetrievalService is a mock of RetrievalService interface.
type MockRetrievalService struct {
	ctrl     *gomock.Controller
	recorder *MockRetrievalServiceMockRecorder
}

// MockRetrievalServiceMockRecorder is the mock recorder for MockRetrievalService.
type MockRetrievalServiceMockRecorder struct {
	mock *MockRetrievalService
}

// NewMockRetrievalService creates a new mock instance.
func NewMockRetrievalService(ctrl *gomock.Controller) *MockRetrievalService {
	mock := &MockRetrievalService{ctrl: ctrl}
	mock.recorder = &MockRetrievalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRetrievalService) EXPECT() *MockRetrievalServiceMockRecorder {
	return m.recorder
}

// ClearSession mocks base method.
func (m *MockRetrievalService) ClearSession(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearSession indicates an expected call of ClearSession.
func (mr *MockRetrievalServiceMockRecorder) ClearSession(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSession", reflect.TypeOf((*MockRetrievalService)(nil).ClearSession), ctx, sessionID)
}

// IndexMessage mocks base method.
func (m *MockRetrievalService) IndexMessage(ctx context.Context, sessionID, userID string, msg message.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexMessage", ctx, sessionID, userID, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// IndexMessage indicates an expected call of IndexMessage.
func (mr *MockRetrievalServiceMockRecorder) IndexMessage(ctx, sessionID, userID, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexMessage", reflect.TypeOf((*MockRetrievalService)(nil).IndexMessage), ctx, sessionID, userID, msg)
}

// SearchSession mocks base method.
func (m *MockRetrievalService) SearchSession(ctx context.Context, sessionID, query string, limit int) ([]message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSession", ctx, sessionID, query, limit)
	ret0, _ := ret[0].([]message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSession indicates an expected call of SearchSession.
func (mr *MockRetrievalServiceMockRecorder) SearchSession(ctx, sessionID, query, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSession", reflect.TypeOf((*MockRetrievalService)(nil).SearchSession), ctx, sessionID, query, limit)
}

// SearchUser mocks base method.
func (m *MockRetrievalService) SearchUser(ctx context.Context, userID, query string, limit int) ([]retrieval.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUser", ctx, userID, query, limit)
	ret0, _ := ret[0].([]retrieval.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUser indicates an expected call of SearchUser.
func (mr *MockRetrievalServiceMockRecorder) SearchUser(ctx, userID, query, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUser", reflect.TypeOf((*MockRetrievalService)(nil).SearchUser), ctx, userID, query, limit)
}
