// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	session "vine-agent/domain/memory/session"
	project "vine-agent/domain/project"

	gomock "github.com/golang/mock/gomock"
)

// MockProjectRepository is a mock of ProjectRepository interface.
type MockProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryMockRecorder
}

// MockProjectRepositoryMockRecorder is the mock recorder for MockProjectRepository.
type MockProjectRepositoryMockRecorder struct {
	mock *MockProjectRepository
}

// NewMockProjectRepository creates a new mock instance.
func NewMockProjectRepository(ctrl *gomock.Controller) *MockProjectRepository {
	mock := &MockProjectRepository{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepository) EXPECT() *MockProjectRepositoryMockRecorder {
	return m.recorder
}

// BindSession mocks base method.
func (m *MockProjectRepository) BindSession(ctx context.Context, projectID, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindSession", ctx, projectID, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindSession indicates an expected call of BindSession.
func (mr *MockProjectRepositoryMockRecorder) BindSession(ctx, projectID, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindSession", reflect.TypeOf((*MockProjectRepository)(nil).BindSession), ctx, projectID, sessionID)
}

// Delete mocks base method.
func (m *MockProjectRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockProjectRepository) Get(ctx context.Context, id string) (*project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProjectRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProjectRepository)(nil).Get), ctx, id)
}

// GetProjectBySession mocks base method.
func (m *MockProjectRepository) GetProjectBySession(ctx context.Context, sessionID string) (*project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectBySession", ctx, sessionID)
	ret0, _ := ret[0].(*project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectBySession indicates an expected call of GetProjectBySession.
func (mr *MockProjectRepositoryMockRecorder) GetProjectBySession(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectBySession", reflect.TypeOf((*MockProjectRepository)(nil).GetProjectBySession), ctx, sessionID)
}

// List mocks base method.
func (m *MockProjectRepository) List(ctx context.Context, userID string) ([]*project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]*project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProjectRepositoryMockRecorder) List(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProjectRepository)(nil).List), ctx, userID)
}

// ListSessionsByProject mocks base method.
func (m *MockProjectRepository) ListSessionsByProject(ctx context.Context, projectID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionsByProject", ctx, projectID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessionsByProject indicates an expected call of ListSessionsByProject.
func (mr *MockProjectRepositoryMockRecorder) ListSessionsByProject(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionsByProject", reflect.TypeOf((*MockProjectRepository)(nil).ListSessionsByProject), ctx, projectID)
}

// ListUnclassifiedSessions mocks base method.
func (m *MockProjectRepository) ListUnclassifiedSessions(ctx context.Context, userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnclassifiedSessions", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnclassifiedSessions indicates an expected call of ListUnclassifiedSessions.
func (mr *MockProjectRepositoryMockRecorder) ListUnclassifiedSessions(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnclassifiedSessions", reflect.TypeOf((*MockProjectRepository)(nil).ListUnclassifiedSessions), ctx, userID)
}

// Save mocks base method.
func (m *MockProjectRepository) Save(ctx context.Context, proj *project.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, proj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockProjectRepositoryMockRecorder) Save(ctx, proj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockProjectRepository)(nil).Save), ctx, proj)
}

// MockProjectService is a mock of ProjectService interface.
type MockProjectService struct {
	ctrl     *gomock.Controller
	recorder *MockProjectServiceMockRecorder
}

// MockProjectServiceMockRecorder is the mock recorder for MockProjectService.
type MockProjectServiceMockRecorder struct {
	mock *MockProjectService
}

// NewMockProjectService creates a new mock instance.
func NewMockProjectService(ctrl *gomock.Controller) *MockProjectService {
	mock := &MockProjectService{ctrl: ctrl}
	mock.recorder = &MockProjectServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectService) EXPECT() *MockProjectServiceMockRecorder {
	return m.recorder
}

// BindSession mocks base method.
func (m *MockProjectService) BindSession(ctx context.Context, projectID, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindSession", ctx, projectID, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindSession indicates an expected call of BindSession.
func (mr *MockProjectServiceMockRecorder) BindSession(ctx, projectID, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindSession", reflect.TypeOf((*MockProjectService)(nil).BindSession), ctx, projectID, sessionID)
}

// CreateProject mocks base method.
func (m *MockProjectService) CreateProject(ctx context.Context, userID, name, desc string, metadata map[string]string) (*project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, userID, name, desc, metadata)
	ret0, _ := ret[0].(*project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockProjectServiceMockRecorder) CreateProject(ctx, userID, name, desc, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockProjectService)(nil).CreateProject), ctx, userID, name, desc, metadata)
}

// DeleteProject mocks base method.
func (m *MockProjectService) DeleteProject(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockProjectServiceMockRecorder) DeleteProject(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockProjectService)(nil).DeleteProject), ctx, id)
}

// GetProject mocks base method.
func (m *MockProjectService) GetProject(ctx context.Context, id string) (*project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, id)
	ret0, _ := ret[0].(*project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockProjectServiceMockRecorder) GetProject(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockProjectService)(nil).GetProject), ctx, id)
}

// GetProjectBySession mocks base method.
func (m *MockProjectService) GetProjectBySession(ctx context.Context, sessionID string) (*project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectBySession", ctx, sessionID)
	ret0, _ := ret[0].(*project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectBySession indicates an expected call of GetProjectBySession.
func (mr *MockProjectServiceMockRecorder) GetProjectBySession(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectBySession", reflect.TypeOf((*MockProjectService)(nil).GetProjectBySession), ctx, sessionID)
}

// ListProjects mocks base method.
func (m *MockProjectService) ListProjects(ctx context.Context, userID string) ([]*project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx, userID)
	ret0, _ := ret[0].([]*project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockProjectServiceMockRecorder) ListProjects(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockProjectService)(nil).ListProjects), ctx, userID)
}

// ListSessionsByProject mocks base method.
func (m *MockProjectService) ListSessionsByProject(ctx context.Context, projectID string) ([]*session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionsByProject", ctx, projectID)
	ret0, _ := ret[0].([]*session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessionsByProject indicates an expected call of ListSessionsByProject.
func (mr *MockProjectServiceMockRecorder) ListSessionsByProject(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionsByProject", reflect.TypeOf((*MockProjectService)(nil).ListSessionsByProject), ctx, projectID)
}

// ListUnclassifiedSessions mocks base method.
func (m *MockProjectService) ListUnclassifiedSessions(ctx context.Context, userID string) ([]*session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnclassifiedSessions", ctx, userID)
	ret0, _ := ret[0].([]*session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnclassifiedSessions indicates an expected call of ListUnclassifiedSessions.
func (mr *MockProjectServiceMockRecorder) ListUnclassifiedSessions(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnclassifiedSessions", reflect.TypeOf((*MockProjectService)(nil).ListUnclassifiedSessions), ctx, userID)
}

// UpdateProject mocks base method.
func (m *MockProjectService) UpdateProject(ctx context.Context, id, name, desc string, metadata map[string]string) (*project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProject", ctx, id, name, desc, metadata)
	ret0, _ := ret[0].(*project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockProjectServiceMockRecorder) UpdateProject(ctx, id, name, desc, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockProjectService)(nil).UpdateProject), ctx, id, name, desc, metadata)
}
